# -*- coding: utf-8 -*-
r"""Generate fig_scaling2_native.tex (fig:scaling) DATA-DRIVEN from scaling_data.json — no hand-typed
numbers. Two panels vs qubits 2L: (a) fermionic magic F1 grows; (b) (N+1)-sector subspace fraction
|S|/dim needed for rel-L1<0.05 falls. Paper identity: large fonts, NEUTRAL dark text (no coloured text),
vibrant DATA colours, 'toward beyond-classical' band below 0.5. Scales to however many L are present."""
# --- DEPOSIT PATHS (repaired 2026-09-18, second pass) -----------------------
# This figure generator addresses every file it reads and writes by a path relative
# to the repository root ('data/...', 'paper/figs/...'), so it only ever worked when
# launched from that root and raised FileNotFoundError from anywhere else.  Rather
# than rewrite every literal -- which risks changing an output byte -- the process's
# working directory is anchored to the repository THIS FILE lives in.  Run from a
# copy of the tree (as src/check_figures.py does), it anchors to that copy, which is
# the behaviour that check wants.  Paths only; no figure content changed.
import os as _os
_os.chdir(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
# ---------------------------------------------------------------------------
import json, sys, numpy as np

# ---------------------------------------------------------------------------
# SUPERSEDED -- REFUSES TO RUN.  Read this before removing the guard.
#
# This generator emits a TWO-panel figure.  The committed
# paper/figs/fig_scaling2_native.tex has THREE panels: panel (c) (absolute support
# |S| and sector dimension D versus 2L) was added by hand on 2026-08-17 and is the
# panel that carries |S| = 22, 246, 2180, 19183, 124407, 824503.  Running this file
# DELETES panel (c), and it does so silently: an adversarial pass on 2026-09-18 ran it
# and then watched `python src/verify.py` report PASS and `pdflatex` produce a 40-page
# document with zero errors and zero undefined references.  The only thing that changed
# was that a third of the figure, and a correction made the same day, were gone.
#
# It would also relabel the shaded band 'toward beyond-classical' -- a claim the
# manuscript disclaims six times.
#
# The committed .tex is AUTHORITATIVE.  If panel (a) and (b) ever need regenerating,
# do it into a scratch directory with --i-know-this-drops-panel-c --out <path> and
# merge by hand.
# ---------------------------------------------------------------------------
_OUT = 'paper/figs/fig_scaling2_native.tex'
if '--i-know-this-drops-panel-c' not in sys.argv:
    for _m in (
        'make_scaling_fig.py: REFUSING TO RUN.',
        '  This generator emits two panels; the committed fig_scaling2_native.tex has',
        '  three. Running it would delete panel (c) and the 19183/824503 correction, and',
        '  nothing downstream would notice. The committed .tex is authoritative.',
        '  If you really mean it:  python src/make_scaling_fig.py '
        '--i-know-this-drops-panel-c --out <scratch path>',
    ):
        print(_m, file=sys.stderr)
    raise SystemExit(2)
if '--out' in sys.argv:
    _OUT = sys.argv[sys.argv.index('--out') + 1]

d=json.load(open('data/scaling_data.json'))
P=sorted(d['points'], key=lambda p:p['L'])
q=[p['qubits'] for p in P]; F=[p['FAF'] for p in P]; fr=[p['frac'] for p in P]
qmin,qmax=min(q),max(q); xlo,xhi=qmin-1.5,qmax+1.5
# panel (a) y-range: nice ceiling above max magic
famax=max(F); ytopA=int(np.ceil((famax*1.12)/5.0)*5);
ytA=list(range(0,ytopA+1,5))
# coordinate strings with value labels (FAF 1 decimal, frac 2 decimals)
coA=" ".join(f"({qi},{fi:.4f})[{fi:.1f}]" for qi,fi in zip(q,F))
coApath=" ".join(f"({qi},{fi:.4f})" for qi,fi in zip(q,F))
coB=" ".join(f"({qi},{fri:.4f})[{fri:.2f}]" for qi,fri in zip(q,fr))
coBpath=" ".join(f"({qi},{fri:.4f})" for qi,fri in zip(q,fr))
xt=",".join(str(qi) for qi in q)
# trend-arrow endpoints (follow the data, offset inward so they don't sit on markers)
axl,axr=q[0]+0.4, q[-1]-0.4
aAy0,aAy1=F[0]+0.8, F[-1]+0.8
aBy0,aBy1=fr[0]-0.04, fr[-1]+0.05

tmpl=r"""% self-contained native pgfplots fragment (fig:scaling) — DATA-DRIVEN from scaling_data.json
% (real Lanczos/Haydock scaling data, L=__LLIST__; U=8). Generated by make_scaling_fig.py — no hand-typed numbers.
\definecolor{scMag}{HTML}{D55E00}\definecolor{scFrac}{HTML}{0072B2}\definecolor{scInk}{HTML}{5B5B5B}
\definecolor{inkPrim}{HTML}{1B1B1B}
\begin{tikzpicture}
\begin{groupplot}[group style={group size=2 by 1, horizontal sep=1.9cm},
  width=8.0cm, height=6.0cm, paperaxis,
  xmin=__XLO__, xmax=__XHI__, xtick={__XT__}, xtick align=outside,
  title style={at={(0,1)},anchor=south west,font=\normalsize\bfseries,yshift=2pt},
  label style={font=\normalsize}, tick label style={font=\normalsize},
  nodes near coords, point meta=explicit symbolic,
  every node near coord/.append style={font=\normalsize,inkPrim,anchor=south,yshift=2pt}]
% ---------- (a) fermionic magic grows ----------
\nextgroupplot[title={(a)~fermionic magic grows},
  xlabel={qubits $\;2L$}, ylabel={fermionic magic $\mathcal{F}_1$}, ymin=0, ymax=__YMAXA__,
  ytick={__YTA__}, ymajorgrids, grid style={draw=black!10}]
\addplot[draw=none,fill=scMag,fill opacity=0.10] coordinates {__COAPATH__} \closedcycle;
\addplot[scMag,line width=1.5pt,mark=*,mark size=3pt,mark options={fill=scMag,draw=white,line width=0.8pt}]
  coordinates {__COA__};
\draw[-{Stealth[length=2mm]},scMag!70,line width=0.8pt] (axis cs:__AXL__,__AAY0__) to[bend left=12] (axis cs:__AXR__,__AAY1__);
% ---------- (b) subspace fraction falls ----------
\nextgroupplot[title={(b)~subspace fraction falls},
  xlabel={qubits $\;2L$}, ylabel={$|\mathcal{S}|/\dim$}, ymin=0, ymax=1.08,
  ytick={0,0.25,0.5,0.75,1}, ymajorgrids, grid style={draw=black!10},
  every node near coord/.append style={font=\normalsize,inkPrim,anchor=south,yshift=2pt}]
\fill[scFrac,fill opacity=0.05] (axis cs:__XLO__,0) rectangle (axis cs:__XHI__,0.5);
% annotation placed in the EMPTY left part of the band (the falling curve enters y<0.5 only past mid-x)
\node[inkPrim,font=\normalsize\itshape,anchor=west] at (axis cs:__ANNX__,0.22) {toward beyond-classical};
\addplot[draw=none,fill=scFrac,fill opacity=0.10] coordinates {__COBPATH__} \closedcycle;
\addplot[scFrac,line width=1.5pt,mark=square*,mark size=2.8pt,mark options={fill=scFrac,draw=white,line width=0.8pt}]
  coordinates {__COB__};
\draw[-{Stealth[length=2mm]},scFrac!70,line width=0.8pt] (axis cs:__AXL__,__ABY0__) to[bend right=10] (axis cs:__AXR__,__ABY1__);
\end{groupplot}
\end{tikzpicture}
"""
out=(tmpl.replace('__LLIST__',",".join(str(p['L']) for p in P))
        .replace('__XLO__',f'{xlo:.1f}').replace('__XHI__',f'{xhi:.1f}').replace('__XT__',xt)
        .replace('__ANNX__',f'{xlo+0.7:.2f}')
        .replace('__YMAXA__',f'{ytopA+0.5:.1f}').replace('__YTA__',",".join(str(y) for y in ytA))
        .replace('__COAPATH__',coApath).replace('__COA__',coA)
        .replace('__COBPATH__',coBpath).replace('__COB__',coB)
        .replace('__AXL__',f'{axl:.2f}').replace('__AXR__',f'{axr:.2f}')
        .replace('__AAY0__',f'{aAy0:.2f}').replace('__AAY1__',f'{aAy1:.2f}')
        .replace('__ABY0__',f'{aBy0:.3f}').replace('__ABY1__',f'{aBy1:.3f}'))
open(_OUT,'w',encoding='utf-8').write(out)
print(f"wrote fig_scaling2_native.tex from {len(P)} points: qubits={q}")
print(f"  FAF={[round(x,2) for x in F]}  frac={[round(x,3) for x in fr]}")
