# -*- coding: utf-8 -*-
"""Rebuild Fig. 5 (fig:akwsampled) as a native TikZ/PGFPlots fragment, honestly.

EVERY number is read from a JSON.  Nothing is typed by hand.  Sources:
  A) release/data/sampled_akw_L8.json   -- the T->infinity limit of the declared protocol
     (sampled_akw.py:47 ranks by the EXACT Born distribution of the time-evolved state:
      that is the infinite-shot limit, not a finite-shot experiment).
  B) release/data/sampled_honest.json   -- the only measured FINITE-SHOT sweep at L=8
     (8 seeds, +-sd).  Different eta (0.15 vs 0.18), different K (18 vs 16 slices) and a
     LOCAL seed c^dag_{0,up} instead of the 16 momentum channels: the gap is declared in
     the caption and in MANIFEST.md, never smoothed over.
Writes fig_akw_sampled_honest.tex + fig5_numbers.json (number -> source manifest).
"""
import json, math, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
# Both roots are derived from this file's own location, so the generator runs in a
# clean clone.  It used to hard-code two absolute paths on the author's machine, one
# of them a session scratch directory that is NOT part of the deposit; the two JSONs
# it read from there are deposited in data/ and were verified field-by-field to be
# numerically identical (only provenance stamps and wall-clock timings differ).
REPO = os.path.dirname(HERE)
DATA = os.path.join(REPO, "data")

A = json.load(open(os.path.join(DATA, "sampled_akw_L8.json")))
B = json.load(open(os.path.join(DATA, "sampled_honest.json")))
C = json.load(open(os.path.join(DATA, "honest_sampling.json")))

man = {}          # manifest: printed number -> where it comes from


def rec(key, val, src):
    man[key] = {"value": val, "source": src}
    return val


# ---------------------------------------------------------------- panel (a) + (b): source A
srcA = "release/data/sampled_akw_L8.json (generated by release/src/sampled_akw.py)"
L_a = rec("panel_a.L", A["L"], srcA + " ['L']")
U_a = rec("panel_a.U", A["U"], srcA + " ['U']")
eta_a = rec("panel_a.eta", A["eta"], srcA + " ['eta']")
fr_a = rec("panel_a.FR", A["frac"], srcA + " ['frac']")
wg = A["wg"]
ov = A["overlay"]
perk = A["per_k"]
mean_a = rec("panel_b.mean_relL1", A["mean_relL1"], srcA + " ['mean_relL1']")
max_a = rec("panel_b.max_relL1", A["max_relL1"], srcA + " ['max_relL1']")
nk = rec("panel_b.n_momenta", len(perk), srcA + " len(['per_k'])")

# Vertical offset of the k-stack: a LAYOUT constant, but derived from the data, not typed --
# step = 1.05 * max(exact overlay).  Self-check: it reproduces the published fragment's
# baselines (0.0007 / 0.7711 / 1.5416) to the 4 decimals that fragment prints.
STEP = 1.05 * max(v for kk in ov for v in ov[kk]["exact"])
rec("layout.offset_step", STEP, srcA + " 1.05*max over ['overlay'][*]['exact'] (layout only)")
ORDER = ["0.0", "0.5", "1.0"]
OFF = {kk: i * STEP for i, kk in enumerate(ORDER)}
klab = {"0.0": r"$k{=}0$", "0.5": r"$k{=}\pi/2$", "1.0": r"$k{=}\pi$"}
for kk, off in OFF.items():
    got = ov[kk]["exact"][0] + off
    ref = {"0.0": 0.0007, "0.5": 0.7711, "1.0": 1.5416}[kk]
    assert abs(got - ref) < 5e-5, ("offset self-check failed", kk, got, ref)

# ---------------------------------------------------------------- panel (c): source B
r8 = [r for r in B["results"] if r["L"] == 8]
assert len(r8) == 1
r8 = r8[0]
P = B["provenance"]["parameters"]
srcB = "release/data/sampled_honest.json (generated by sampled_honest.py)"
eta_b = rec("panel_c.eta", P["eta_over_t"], srcB + " ['provenance']['parameters']['eta_over_t']")
K_b = rec("panel_c.K_slices", P["K_slices"], srcB + " [...]['K_slices']")
nseed = rec("panel_c.n_seeds", P["n_seeds"], srcB + " [...]['n_seeds']")
thr = rec("panel_c.threshold", P["threshold_relL1"], srcB + " [...]['threshold_relL1']")
op_b = rec("panel_c.operator", P["operator"], srcB + " [...]['operator']")
dim8 = rec("panel_c.dim_Np1", r8["dim_Np1"], srcB + " results[L=8]['dim_Np1']")
sw = r8["shot_sweep"]
rows = []
for s in sw:
    rows.append(dict(T=s["T"], m=s["relL1_mean"], sd=s["relL1_std"],
                     f=s["frac_mean"], fsd=s["frac_std"], S=s["S_mean"], npass=s["n_pass"]))
rec("panel_c.rows", rows, srcB + " results[L=8]['shot_sweep'][*] "
    "(T, relL1_mean, relL1_std, frac_mean, frac_std, S_mean, n_pass)")
top = rows[-1]
rec("panel_c.top_budget_T", top["T"], srcB + " results[L=8]['shot_sweep'][-1]['T']")
rec("panel_c.top_budget_frac", top["f"], srcB + " ...['frac_mean']")
rec("panel_c.top_budget_fracsd", top["fsd"], srcB + " ...['frac_std']")
rec("panel_c.top_budget_relL1", top["m"], srcB + " ...['relL1_mean']")
rec("panel_c.top_budget_sd", top["sd"], srcB + " ...['relL1_std']")
rec("panel_c.oracle_frac_local", r8["oracle"]["fraction"], srcB + " results[L=8]['oracle']['fraction']")
rec("cross.honest_protocol", C["provenance"]["protocol"],
    "release/data/honest_sampling.json ['provenance']['protocol']")

# ---------------------------------------------------------------- emit


def coords(xs, ys, prec=4):
    return " ".join("(%.3f,%.*f)" % (x, prec, y) for x, y in zip(xs, ys))


def sci(x, nd=2):
    s = "%.*e" % (nd, x)
    mant, ex = s.split("e")
    return r"%s\times10^{%d}" % (mant, int(ex))


out = []
w = out.append
w(r"% Fig. 5 REBUILT 2026-09-18 -- honest labelling of the sampling limit.")
w(r"% Panels (a),(b): release/data/sampled_akw_L8.json.  sampled_akw.py:47 ranks by the EXACT Born")
w(r"%   distribution of the time-evolved state, so this is the T->infinity limit of the declared")
w(r"%   protocol, NOT a finite-shot experiment.  Labelled as such in the title, legend and caption.")
w(r"% Panel (c): release/data/sampled_honest.json, results[L=8]['shot_sweep'] -- the measured")
w(r"%   finite-shot sweep, 8 seeds, +-1 s.d. band.  DIFFERENT configuration (eta=0.15t, K=18 slices,")
w(r"%   local seed c^dag_{0,up}, addition branch only): declared in the caption.  No extrapolation.")
w(r"% Every coordinate and every printed number is emitted by make_fig5_honest.py from those JSONs.")
w(r"\definecolor{akExact}{HTML}{1B1B1B}\definecolor{akSamp}{HTML}{D55E00}"
  r"\definecolor{akInk}{HTML}{1B1B1B}\definecolor{akShot}{HTML}{0072B2}")
w(r"\begin{tikzpicture}")

# ---------- panel (a) ----------
w(r"\begin{axis}[name=pa, width=14.05cm, height=6.3cm, paperaxis,")
w(r"  title={(a)~exact $A(k,\omega)$ versus the reconstruction on the top-$%d\%%$ Born subspace},"
  % round(fr_a * 100))
w(r"  title style={at={(0,1)},anchor=south west,font=\normalsize\bfseries,yshift=15pt},")
w(r"  label style={font=\normalsize}, tick label style={font=\footnotesize},")
w(r"  xlabel={$\omega-E_0\ (t)$}, ylabel={$A(k,\omega)$ (offset by $k$)},")
w(r"  xmin=-9,xmax=9, ymin=-0.3,ymax=2.85, ytick=\empty, xtick={-8,-6,-4,-2,0,2,4,6,8},")
w(r"  legend style={font=\footnotesize,at={(1,1.005)},anchor=south east,legend columns=2,"
  r"draw=none,fill=none,/tikz/every even column/.append style={column sep=10pt}},legend cell align=left]")
first = True
for kk in ORDER:
    off = OFF[kk]
    ex = [y + off for y in ov[kk]["exact"]]
    sa = [y + off for y in ov[kk]["sampled"]]
    w(r"\addplot[akExact,line width=1.2pt,fill=akExact,fill opacity=0.06] coordinates {%s} \closedcycle;"
      % coords(wg, ex))
    w(r"\addplot[akSamp,line width=1.1pt,dash pattern=on 4pt off 2.5pt] coordinates {%s};"
      % coords(wg, sa))
    if first:
        w(r"\addlegendentry{exact (Haydock)}")
        w(r"\addlegendentry{top-$%d\%%$ Born subspace, infinite-shot limit $T\rightarrow\infty$}"
          % round(fr_a * 100))
        first = False
    w(r"\node[akInk,font=\footnotesize,anchor=west] at (axis cs:-8.75,%.4f) {%s};"
      % (off + 0.155, klab[kk]))
w(r"\end{axis}")

# ---------- panel (b) ----------
ks = sorted(float(k) for k in perk)
ys = [perk["%.3f" % k]["relL1"] for k in ks]
w(r"\begin{axis}[name=pb, width=6.0cm, height=6.0cm, paperaxis,")
w(r"  at={(pa.south west)}, anchor=north west, yshift=-2.5cm,")
w(r"  title={(b)~per-momentum error},")
w(r"  title style={at={(0,1)},anchor=south west,font=\normalsize\bfseries,yshift=15pt},")
w(r"  label style={font=\normalsize}, tick label style={font=\footnotesize},")
w(r"  xlabel={$k/\pi$}, ylabel={relative-$L_1$},")
w(r"  xmin=-0.12,xmax=2.15, ymin=0, ymax=0.0092, xtick={0,0.5,1,1.5},")
w(r"  ytick={0,0.001,0.002,0.003}, scaled y ticks=false,")
w(r"  yticklabel style={/pgf/number format/fixed,/pgf/number format/precision=3},")
w(r"  ymajorgrids, grid style={draw=black!10}]")
w(r"\addplot[akSamp,only marks,mark=*,mark size=2.6pt,"
  r"mark options={fill=akSamp,draw=white,line width=0.6pt}] coordinates {%s};"
  % " ".join("(%.3f,%.6f)" % (k, y) for k, y in zip(ks, ys)))
w(r"\node[akInk,font=\scriptsize,anchor=north west,align=left] at (axis cs:-0.08,0.0090)"
  r" {infinite-shot limit $T\rightarrow\infty$\\all %d momenta, both branches\\mean $%s$\\max $%s$};" % (nk, sci(mean_a), sci(max_a)))
w(r"\end{axis}")

# ---------- panel (c) ----------
Ts = [r["T"] for r in rows]
ms = [r["m"] for r in rows]
sds = [r["sd"] for r in rows]
up = [r["m"] + r["sd"] for r in rows]
lo = [r["m"] - r["sd"] for r in rows]
assert min(lo) > 0
fr = [r["f"] for r in rows]
relspread = max(r["sd"] / r["m"] for r in rows)
rec("panel_c.max_relative_sd", relspread,
    srcB + " max over results[L=8]['shot_sweep'][*] of relL1_std/relL1_mean")
band = list(zip(Ts, up)) + list(zip(reversed(Ts), reversed(lo)))
w(r"\begin{axis}[name=pc, width=6.5cm, height=6.0cm, paperaxis,")
w(r"  at={(pb.south east)}, anchor=south west, xshift=1.75cm,")
w(r"  title={(c)~measured finite-shot cost},")
w(r"  title style={at={(0,1)},anchor=south west,font=\normalsize\bfseries,yshift=15pt},")
w(r"  label style={font=\normalsize}, tick label style={font=\footnotesize},")
w(r"  xmode=log, ymode=log, xlabel={total shots $T$}, ylabel={relative-$L_1$},")
w(r"  xmin=8, xmax=9e6, ymin=2.4e-3, ymax=14.0,")
w(r"  xtick={10,1000,100000,10000000}, ytick={0.001,0.01,0.1,1},")
w(r"  ymajorgrids, xmajorgrids, grid style={draw=black!10},")
w(r"  extra x ticks={%s}," % ",".join("%d" % T for T in Ts))
w(r"  extra x tick labels={%s}," % ",".join("%.3f" % f for f in fr))
w(r"  extra x tick style={xticklabel pos=upper,"
  r" xtick style={draw=none}, grid=none,"    # marks for the upper labels are drawn by hand at the TOP
  r" xticklabel style={font=\tiny,akShot}}]")
w(r"\addplot[draw=none,fill=akShot,fill opacity=0.28,forget plot] coordinates {%s} \closedcycle;"
  % " ".join("(%d,%.6g)" % (x, y) for x, y in band))
w(r"\addplot[akShot,line width=1.1pt,mark=*,mark size=2.2pt,"
  r"mark options={fill=akShot,draw=white,line width=0.6pt},"
  r"error bars/.cd,y dir=both,y explicit,"
  r"error bar style={akShot,line width=0.6pt},error mark options={akShot,mark size=1.6pt}]"
  r" coordinates {%s};"
  % " ".join("(%d,%.6g) +- (0,%.6g)" % (x, y, e) for x, y, e in zip(Ts, ms, sds)))
w(r"\addplot[akInk,densely dotted,line width=0.8pt,forget plot] coordinates {(8,%g) (9e6,%g)};"
  % (thr, thr))
w(r"\node[akInk,font=\tiny,anchor=south west] at (axis cs:9.5,%g) {acceptance threshold %.2f};"
  % (thr * 1.16, thr))
w(r"\node[akShot,font=\tiny,anchor=north west,align=left] at (axis cs:9.5,8.2)"
  r" {upper axis: sector fraction reached\\%d seeds; band and bars $\pm1$ s.d.};" % nseed)
w(r"\node[akInk,font=\scriptsize,anchor=south west,align=left] at (axis cs:10,2.55e-3)"
  r" {$T=%s$ shots:\\$|\mathcal S|/\dim=%.3f\pm%.4f$\\rel-$L_1=(%.2f\pm%.2f)\times10^{-3}$};"
  % (sci(float(top["T"])), top["f"], top["fsd"], top["m"] * 1e3, top["sd"] * 1e3))
w(r"% D14: real tick marks for the upper (fraction) axis.  paperaxis puts ticks on the")
w(r"% left/bottom only, so these are drawn outward at the top frame.  X positions come")
w(r"% from the same budgets Ts and the same log limits as the labels; 2.2pt is layout.")
XLO, XHI = 8.0, 9e6
for _T in Ts:
    _rel = (math.log10(_T) - math.log10(XLO)) / (math.log10(XHI) - math.log10(XLO))
    assert 0.0 < _rel < 1.0, _T
    w(r"\draw[akShot,line width=0.4pt] (rel axis cs:%.6f,1) -- (rel axis cs:%.6f,1.021);" % (_rel, _rel))
w(r"\end{axis}")
w(r"\end{tikzpicture}")

tex = "\n".join(out) + "\n"
open(os.path.join(REPO, "paper", "figs", "fig_akw_sampled_honest.tex"), "w", encoding="utf-8").write(tex)

# ---------------------------------------------------------------- caption (English)
# K and dt of the Fig.-5 run are NOT stored in sampled_akw_L8.json.  Parse them out of the
# script that produced it rather than typing them (release/src/sampled_akw.py, line 31).
_src = open(os.path.join(REPO, "src", "sampled_akw.py"), encoding="utf-8", errors="replace").read()
_m = re.search(r"L,\s*U,\s*t,\s*eta,\s*K,\s*dt\s*=\s*(.+)", _src)
assert _m, "could not parse the parameter line of sampled_akw.py"
_vals = [float(x) for x in _m.group(1).split(",")]
K_a, dt_a = int(_vals[4]), _vals[5]
assert (int(_vals[0]), _vals[1], _vals[3]) == (L_a, U_a, eta_a), "sampled_akw.py disagrees with its own JSON"
rec("panel_a.K_slices", K_a, "release/src/sampled_akw.py parameter line (L,U,t,eta,K,dt)")
rec("panel_a.dt", dt_a, "release/src/sampled_akw.py parameter line (L,U,t,eta,K,dt)")
Ssub = int(round(fr_a * dim8))          # sampled_akw.py:47  kk = round(FR*nS)
rec("caption.subspace_size", Ssub, srcA + " round(['frac'] * 3920) -- sampled_akw.py:47")
nsnap = K_b + 1
# penalty of finite-shot selection vs the infinite-shot ranking, at MATCHED |S| (measured)
pen = {}
for r in B["results"]:
    if r["L"] in (6, 8):
        m = r["matched_subspace"][0]
        pen[r["L"]] = (m["fraction"], m["penalty_factor_topm"])
rec("caption.matched_penalty", pen,
    srcB + " results[L]['matched_subspace'][0] (fraction, penalty_factor_topm), L=6,8")

cap = r"""\textbf{The momentum-resolved spectral function on a Born-ranked subspace, and what that
subspace costs in shots.}
\textbf{(a)}~Exact Haydock $A(k,\omega)$ (solid, shaded) and the reconstruction obtained by
diagonalising the top-%(frpc)d\%% of the $(N{\pm}1)$ sector under the time-averaged Born weight of the
evolved state (dashed), at three momenta ($k=0,\pi/2,\pi$; Hubbard chain, $L=%(L)d$, $U/t=%(U)g$,
$\eta=%(etaA)g\,t$, $K=%(KA)d$ time slices, $\delta t=%(dtA)g$; curves offset vertically by $k$).
The subspace is $%(Ssub)d$ of the $%(dim)d$ determinants of each channel. The ranking in
\texttt{src/sampled\_akw.py} is taken on the \emph{exact} Born distribution, so panels (a) and (b)
are the \textbf{infinite-shot limit} $T\rightarrow\infty$ of the protocol, not a finite-shot experiment;
no shot budget is attached to them.
\textbf{(b)}~Relative-$L_1$ error of that reconstruction at all %(nk)d physical momenta, addition and
removal branch summed: mean $%(meansci)s$, maximum $%(maxsci)s$.
\textbf{(c)}~What a finite shot budget buys, measured. Same chain and the same sector dimension
($L=%(L)d$, $\dim(N{+}1)=%(dim)d$) but a separate run: local seed $c^{\dagger}_{0\uparrow}\ket{\Psi_0}$,
$\eta=%(etaB)g\,t$, $K=%(K)d$ time slices, $T$ shots split evenly over the %(nsnap)d snapshots, subspace
= the support observed in those $T$ shots, %(ns)d independent seeds. Markers are the seed mean; the
shaded band and the error bars are $\pm1$ s.d.\ over the %(ns)d seeds (at most $%(spread).1f\%%$ of the
mean at any budget, hence thinner than the line). Upper axis: the sector fraction $|\mathcal S|/\dim$
reached at that budget; the dotted line is the acceptance threshold rel-$L_1=%(thr).2f$ used by the
resource scan. At the largest budget measured, $T=%(Ttop)s$ shots, the observed subspace covers
$%(ftop).3f\pm%(ftopsd).4f$ of the sector and the reconstruction reaches
rel-$L_1=(%(mtop).2f\pm%(sdtop).2f)\times10^{-3}$.
\textbf{Declared gap:} no finite-shot run exists for the configuration of (a)--(b)
($\eta=%(etaA)g\,t$, $K=%(KA)d$, the %(nchan)d momentum channels), and the %(frpc)d\%% fraction of (a)--(b)
is above every budget measured in (c), whose largest reaches $%(ftop).3f$. Panel (c) is the closest
measured surrogate, not the same experiment, and nothing here is extrapolated; note also that the
budget in (c) buys one channel, whereas (a)--(b) reconstruct %(nchan)d. Where the two
selections were compared at \emph{matched} subspace size in the run of (c), finite-shot selection was
worse than the infinite-shot ranking by $%(pen6).2f\times$ at $L=6$ (fraction $%(fr6).2f$) and
$%(pen8).2f\times$ at $L=8$ (fraction $%(fr8).2f$); panel (b) is therefore optimistic with respect to a
finite-shot experiment on a subspace of the same size.""" % dict(
    frpc=round(fr_a * 100), KA=K_a, dtA=dt_a, L=L_a, U=U_a, etaA=eta_a, etaB=eta_b, K=K_b, nsnap=nsnap,
    Ssub=Ssub, dim=dim8, nk=nk, meansci=sci(mean_a), maxsci=sci(max_a), ns=nseed, spread=relspread * 100,
    thr=thr, Ttop=sci(float(top["T"])), ftop=top["f"], ftopsd=top["fsd"],
    mtop=top["m"] * 1e3, sdtop=top["sd"] * 1e3, nchan=2 * nk,
    pen6=pen[6][1], fr6=pen[6][0], pen8=pen[8][1], fr8=pen[8][0])
CAPHDR = ("%% Caption for fig_akw_sampled_honest.tex.  Drop-in replacement for the caption of\n"
          "%% fig:akwsampled in results.tex (the label is kept so every \\ref still resolves).\n")
cap_wrapped = CAPHDR + "\\caption{" + cap + "}\n\\label{fig:akwsampled}\n"
open(os.path.join(REPO, "paper", "figs", "fig_akw_sampled_honest_caption.tex"), "w", encoding="utf-8").write(cap_wrapped)
open(os.path.join(REPO, "paper", "figs", "fig_akw_sampled_honest_caption_macro.tex"), "w", encoding="utf-8").write(
    "\\newcommand{\\figFiveCaption}{%\n" + cap + "}\n")
print("wrote fig5_caption.tex (%d chars); |S|=%d of %d; penalties %s" % (len(cap), Ssub, dim8, pen))
json.dump(man, open(os.path.join(REPO, "data", "sampled_akw_figure_numbers.json"), "w"), indent=1)
print("wrote fig_akw_sampled_honest.tex  (%d bytes)" % len(tex))
print("panel a/b: L=%d U=%g eta=%g FR=%g  mean=%.6g max=%.6g nk=%d"
      % (L_a, U_a, eta_a, fr_a, mean_a, max_a, nk))
print("panel c  : eta=%g K=%d seeds=%d thr=%g dim=%d op=%s" % (eta_b, K_b, nseed, thr, dim8, op_b))
for r in rows:
    print("   T=%9d  frac=%.4f+-%.4f  relL1=%.6f+-%.6f  n_pass=%d"
          % (r["T"], r["f"], r["fsd"], r["m"], r["sd"], r["npass"]))
print("max relative s.d. over the 7 budgets: %.4f" % relspread)
