# -*- coding: utf-8 -*-
r"""HARDWARE figure (fig:heron), TWO panels, emitted as an \input FRAGMENT so \normalsize == the paper
body size EXACTLY (no include-scaling font games). Rules enforced: (1) BOTH real hardware runs shown;
(2) every font = body \normalsize; (3) all text neutral (inkPrim/inkMute) -- colour only in data;
(4) all text inside the axes, never over a curve. Panels:
(a) ibm_fez -- Hubbard L=6 spectral function A(omega) (full-sector coverage -> exact).
(b) ibm_marrakesh -- N2 ground-state energy vs recovery step: the MEAN over 8 recovery seeds on the
    cached device counts, with a per-step error bar = +-1 s.d. across those 8 seeds (job da125f2ein7c73bcsqs0,
    no new QPU). The noisy device converges to 0.59+-0.14 mHa (below chemical accuracy) and beats the
    noiseless statevector simulation of the same circuit (29.5 mHa).
Data: heron_spectral.json, hw_lucj_n2_result.json (dE_hist_mean / dE_hist_std -- the full per-seed run
log; NO hand-typed numbers)."""
import json, numpy as np
h=json.load(open('data/heron_spectral.json')); g=np.array(h['grid'])
A=np.array(h['A_hw'])   # the REAL ibm_fez hardware-sampled reconstruction (==A_exact to 8e-15 by full-sector coverage)
with open('paper/figs/heron_hot.dat','w') as f:
    f.write('w A\n')
    for w,a in zip(g,A): f.write(f'{w:.4f} {a:.5f}\n')
Amax=float(A.max())

n=json.load(open('data/hw_lucj_n2_result.json')); fci=n['e_fci']
# noiseless statevector trajectory (same circuit), dE to FCI in mHa
sim=[abs(e-fci)*1000 for e in n['hist_sim']]
simc=" ".join(f"({i},{v:.3f})" for i,v in enumerate(sim))
# REAL hardware: 8-seed recovery MEAN per step + a +-1 s.d. ENVELOPE (shaded band) per step.
mean=n['dE_hist_mean']; std=n['dE_hist_std']
hwce=" ".join(f"({i},{m:.3f})+-(0,{s:.3f})" for i,(m,s) in enumerate(zip(mean,std)))    # mean curve + per-point error bar
hwhi=" ".join(f"({i},{m+s:.3f})"        for i,(m,s) in enumerate(zip(mean,std)))        # band upper = mean+std
hwlo=" ".join(f"({i},{max(m-s,1e-3):.3f})" for i,(m,s) in enumerate(zip(mean,std)))     # band lower = mean-std (log-safe)
dEm=n['dE_mean_mHa']; dEs=n['dE_std_mHa']         # converged 0.59 +- 0.14

frag=r"""% fragment: \input into the figure environment -> \normalsize equals the body font exactly.
% AUTO-GENERATED by src/make_hardware_hero.py from data/hw_lucj_n2_result.json -- no hand-typed numbers.
\definecolor{inkPrim}{HTML}{1B1B1B}\definecolor{inkMute}{HTML}{6E6E6E}
\definecolor{warmFill}{HTML}{E8770C}\definecolor{warmLine}{HTML}{7A1E10}
\definecolor{hwWarm}{HTML}{C4360C}\definecolor{simSlate}{HTML}{9AA1AC}\definecolor{band}{HTML}{ECE7DF}
\begin{tikzpicture}[font=\rmfamily]
\pgfplotsset{hpanel/.style={width=8.5cm,height=6.0cm,axis line style={inkPrim,line width=0.6pt},
  tick style={inkPrim,line width=0.6pt},tick label style={font=\normalsize},label style={font=\normalsize},
  title style={font=\normalsize,yshift=1pt},ymajorgrids,major grid style={inkMute,opacity=0.10,line width=0.3pt}}}
% ===================== (a) ibm_fez : spectral function A(omega) =====================
% CLEAN: curve + title only; all technical detail (shots, mitigation, coverage) lives once, in the caption.
\begin{axis}[name=axa,hpanel,
  title={(a)\ \ \texttt{ibm\_fez} $\cdot$ 12 qubits: \ $A(\omega)$},
  xlabel={frequency \ $\omega-E_0$}, ylabel={$A(\omega)$},
  xmin=__XMIN__,xmax=__XMAX__,ymin=0,ymax=__YMAXA__]
  \addplot[draw=none,fill=warmFill,fill opacity=0.28] table[x=w,y=A]{figs/heron_hot.dat} \closedcycle;
  \addplot[warmLine,line width=1.3pt] table[x=w,y=A]{figs/heron_hot.dat};
\end{axis}
% ===================== (b) ibm_marrakesh : N2 ground-state energy =====================
% CLEAN: two curves + which-is-which + the two headline numbers; specs/jobs live once, in the caption.
\begin{axis}[name=axb,hpanel,at={(axa.south east)},anchor=south west,xshift=1.4cm,
  title={(b)\ \ \texttt{ibm\_marrakesh} $\cdot$ 24 qubits: \ $\mathrm{N_2}$ energy},
  xlabel={configuration-recovery step}, ylabel={error to FCI \ (mHa)},
  ymode=log,xmin=-0.35,xmax=4.55,ymin=0.28,ymax=90,
  xtick={0,1,2,3,4},ytick={0.5,1,3,10,30},yticklabels={$0.5$,$1$,$3$,$10$,$30$}]
  \fill[band,opacity=0.72] (axis cs:-0.35,0.28) rectangle (axis cs:4.55,1.6);
  \node[anchor=south west,font=\normalsize,inkPrim] at (axis cs:-0.28,0.42) {chem.\ accuracy};
  % REAL hardware recovery: MEAN over 8 recovery seeds on the SAME cached ibm_marrakesh counts
  % (job da125f2ein7c73bcsqs0, no new QPU); shaded envelope = +-1 s.d. across the 8 seeds at every step.
  \addplot[draw=none,name path=hwhi,forget plot] coordinates {__HWHI__};
  \addplot[draw=none,name path=hwlo,forget plot] coordinates {__HWLO__};
  \addplot[warmFill,fill opacity=0.30,forget plot] fill between[of=hwhi and hwlo];
  \addplot[simSlate,line width=1.4pt,dash pattern=on 5pt off 3pt,mark=square,mark size=2.6pt,
           mark options={draw=simSlate,fill=white,line width=1pt}] coordinates {__SIMC__};
  % mean over 8 seeds + a capped +-1 s.d. error bar at EVERY step, on top of the shaded envelope
  \addplot[hwWarm,line width=2.2pt,mark=*,mark size=3.0pt,mark options={fill=hwWarm,draw=white,line width=0.7pt},
     error bars/.cd,y dir=both,y explicit,error bar style={hwWarm,line width=1.1pt},
     error mark=-,error mark options={rotate=90,hwWarm,line width=1.1pt,mark size=4pt}]
     coordinates {__HWCE__};
  % which curve is which: a leader from each label lands ON its own curve; plus the two headline numbers
  \node[anchor=south,font=\normalsize,inkPrim] (nl) at (axis cs:1.85,44)
    {noiseless (same circuit), $29.5$~mHa};
  \draw[-{Stealth[length=1.7mm]},inkPrim,line width=0.5pt] (nl.south) -- (axis cs:1.55,30.0);
  \node[anchor=south,align=center,font=\normalsize,inkPrim] (nh) at (axis cs:3.05,5.2)
    {noisy hardware\\$__DEM__\pm__DES__$~mHa};
  \draw[-{Stealth[length=1.7mm]},inkPrim,line width=0.5pt] (nh.south) -- (axis cs:3.0,1.15);
\end{axis}
\end{tikzpicture}
"""
out=(frag.replace('__XMIN__',f'{g[0]:.2f}').replace('__XMAX__',f'{g[-1]:.2f}')
        .replace('__YMAXA__',f'{Amax*1.10:.3f}').replace('__SIMC__',simc)
        .replace('__HWHI__',hwhi).replace('__HWLO__',hwlo).replace('__HWCE__',hwce)
        .replace('__DEM__',f'{dEm:.2f}').replace('__DES__',f'{dEs:.2f}'))
open('paper/figs/fig_hardware_hero_frag.tex','w',encoding='utf-8').write(out)
print(f'wrote fig_hardware_hero_frag.tex | 8-seed envelope (mean+-std) per step: '
      + ", ".join(f'{m:.2f}+-{s:.2f}' for m,s in zip(mean,std)))
